//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNS_Note
    {
        public string SNS_Note_ID { get; set; }
        public string SNS_Note_PostID { get; set; }
        public string SNS_Note_Title { get; set; }
        public string SNS_Note_Post_Text { get; set; }
        public Nullable<int> SNS_Note_Reply_ID { get; set; }
        public System.DateTime SNS_Note_Date { get; set; }
    }
}
