//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SNS_User_Info
    {
        public string SNS_User_ID { get; set; }
        public string SNS_User_Email { get; set; }
        public string SNS_User_Name { get; set; }
        public string SNS_User_PassWord { get; set; }
        public Nullable<int> SNS_User_Type { get; set; }
    }
}
